version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "Terraform"
    assignees:
      - "46ki75"
    reviewers:
      - "46ki75"
